#!/usr/bin/env python3
"""Generate deterministic synthetic plumbing data; this is not weather evidence."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=Path("runs/model-fixture"))
    arguments = parser.parse_args()
    output_directory = arguments.output_dir.resolve()
    output_directory.mkdir(parents=True, exist_ok=True)

    observed = np.zeros((4, 16, 16, 1), dtype=np.float32)
    for time_index in range(observed.shape[0]):
        start = 2 + time_index
        observed[time_index, start : start + 4, start : start + 4, 0] = time_index + 1
    np.save(output_directory / "observed.npy", observed)

    event = {
        "schema_version": "1.0",
        "event_id": "synthetic-model-plumbing-001",
        "mode": "synthetic",
        "event_time_utc": "2026-01-01T00:15:00Z",
        "timestamps_utc": [
            "2026-01-01T00:00:00Z",
            "2026-01-01T00:05:00Z",
            "2026-01-01T00:10:00Z",
            "2026-01-01T00:15:00Z",
        ],
        "observed_array_path": "observed.npy",
        "channel_names": ["synthetic_test_value"],
        "channel_units": ["arbitrary_demo_units"],
        "quality_mask_path": None,
        "sources": [
            {
                "id": "deterministic-model-fixture-generator",
                "availability": "synthetic",
                "provenance": (
                    "Generated by scripts/generate-model-fixture.py; "
                    "not meteorological observations"
                ),
            }
        ],
        "grid": {
            "native_spacing_km": None,
            "effective_spacing_km": None,
            "crs": None,
            "bounds_wgs84": None,
        },
    }
    manifest_path = output_directory / "event.json"
    manifest_path.write_text(json.dumps(event, indent=2) + "\n", encoding="utf-8")
    print(manifest_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
